// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rathbvccsiwgxcvzflwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhdGhidmNjc2l3Z3hjdnpmbHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTc0NTYsImV4cCI6MjA2MTY3MzQ1Nn0.FaemVYyKm9a9WVI0tCjb3tlcwJnqfZG1rize47w2ycY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);